### ISSUE TITLE
Lack of Support for Additional Conformance Test Flags

### ISSUE THREAD

**Issue by rjsadow** [kubernetes-sigs/hydrophone#95]
Sometimes control plane nodes are not schedulable by default, requiring the use of additional conformance flags like `--allowed-not-ready-nodes=3` for tests. However, Hydrophone does not currently offer a comprehensive mapping to the conformance image options.

ref: https://kubernetes.slack.com/archives/C78F00H99/p1705427311573629
ref: https://github.com/kubernetes/kubernetes/blob/9b5e2dc54d2315402a462e75c168bfc4ce28ecf3/test/e2e/framework/test_context.go#L363

**Comment by rjsadow** [comment]
I don't think it's reasonable or maintainable to keep a consistent mapping for all conformance image options. Likely the better solution would be to impliment a catch all flag that passes extra flags to the conformance image args. I don't have a good example for how to do that off the bat.

**Comment by reetasingh** [comment]
I am interested in this . @Hii-Arpit are you looking at catch all flag option or specifically --allow-not-ready-nodes option? I can work on the other one

**Comment by reetasingh** [comment]
@rjsadow I thought about a solution for `catch all flag` option
1. Implement a CLI flag which takes multiple key value pair as input `rootCmd.Flags().VarP(&keyValue, "keyvalue", "k", "Multiple key/value pairs (e.g., key1=value1,key2=value2)")`. Since we now use viper for config management we can also pass this in a config file to not make it look  messy on command line
2. for each of the defined key value pair pass it as input in the env variable list  for the container  by adding `Name =  "E2E_<key>" and  Value = <value>` https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/service/init.go#L149
since its a catch all flag, we will not be able to to do validation 

what do you think?

**Comment by rjsadow** [comment]
I believe we'll need to pass any extra args we tak in via flags to the pod as an array of args. The E2E keys only work for a small subset of variables (https://github.com/kubernetes/kubernetes/blob/02aaad0de94708b00e95ba6e809ac07d34eff61c/test/conformance/image/go-runner/const.go#L35-L42) and don't have a direct one for one mapping to all possible conformance flags listed here https://github.com/kubernetes/kubernetes/blob/9b5e2dc54d2315402a462e75c168bfc4ce28ecf3/test/e2e/framework/test_context.go#L349-L466

**Comment by reetasingh** [comment]
I will try with passing the arguments to the constructor. Also, looks like there is option to pass extra through E2E keys using E2E_EXTRA_ARGS https://github.com/kubernetes/kubernetes/blob/02aaad0de94708b00e95ba6e809ac07d34eff61c/test/conformance/image/go-runner/const.go#L50

**Comment by rjsadow** [comment]
Hey @Hii-Arpit, I'm going to reassign this issue to @reetasingh , her PR looks like it's going to cover all cases for adding extra arguments for users and we'd like to get this issue resolved to unblock some users from testing hydrophone. Feel free to reach out in slack or check out other issues that you'd like to help with! 

/unassign @Hii-Arpit 
/assign @reetasingh

**Comment by Hii-Arpit** [comment]
Thanks for informing me.
